package store

// Settings is the single row holding your business details and form defaults.
type Settings struct {
	BusinessName        string
	BusinessTagline     string
	AddressLine1        string
	AddressLine2        string
	CityStateZip        string
	Email               string
	Phone               string
	TaxID               string
	DefaultRateCents    int64
	DefaultTermsDays    int64
	PaymentInstructions string
	Notes               string
	FooterMessage       string
}

// ClientData is the editable part of a client.
type ClientData struct {
	Name             string
	Attn             string
	AddressLine1     string
	AddressLine2     string
	CityStateZip     string
	Email            string
	DefaultProject   string
	DefaultContract  string
	DefaultPO        string
	DefaultRateCents *int64 // nil falls back to Settings
	DefaultTermsDays *int64 // nil falls back to Settings
	Archived         bool
}

// RateCents is the client's own default rate, or 0 if it has none.
func (c ClientData) RateCents() int64 {
	if c.DefaultRateCents == nil {
		return 0
	}
	return *c.DefaultRateCents
}

// TermsDays is the client's own default terms, or 0 if it has none.
func (c ClientData) TermsDays() int64 {
	if c.DefaultTermsDays == nil {
		return 0
	}
	return *c.DefaultTermsDays
}

type Client struct {
	ID int64
	ClientData
	CreatedAt    string
	InvoiceCount int64 // only populated by ListClients
}

// BusinessSnapshot is your business block as copied onto an invoice.
type BusinessSnapshot struct {
	BusinessName         string
	BusinessTagline      string
	BusinessAddressLine1 string
	BusinessAddressLine2 string
	BusinessCityStateZip string
	BusinessEmail        string
	BusinessPhone        string
	BusinessTaxID        string
}

// ClientSnapshot is the client's billing address as copied onto an invoice.
type ClientSnapshot struct {
	ClientName         string
	ClientAttn         string
	ClientAddressLine1 string
	ClientAddressLine2 string
	ClientCityStateZip string
	ClientEmail        string
}

// InvoiceData is every column of an invoice that create and update write.
type InvoiceData struct {
	Number   string
	ClientID int64 // 0 means NULL: no client, or the client was deleted
	BusinessSnapshot
	ClientSnapshot
	ProjectName         string
	ContractRef         string
	PONumber            string
	InvoiceDate         string
	PeriodStart         string
	PeriodEnd           string
	TermsDays           int64
	DueDate             string
	ExpensesCents       int64
	DiscountCents       int64
	PaymentInstructions string
	Notes               string
	FooterMessage       string
}

type Invoice struct {
	ID int64
	InvoiceData
	GeneratedAt string
	UpdatedAt   string

	SubtotalCents int64
	TotalHours    float64
	TotalCents    int64
}

type LineItem struct {
	ID          int64
	InvoiceID   int64
	Position    int64
	WorkDate    string
	Description string
	Detail      string
	Hours       float64
	RateCents   int64
	AmountCents int64 // generated by SQLite
}

type InvoiceStats struct {
	Count      int64
	TotalCents int64
	TotalHours float64
}
